# Generated by Django 5.2.7 on 2025-10-10 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre del producto')),
                ('referencia', models.CharField(max_length=35, unique=True, verbose_name='Referencia del producto')),
                ('stock', models.IntegerField(verbose_name='Cantidad en stock')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio del producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del producto')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del producto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_productos.categoria', verbose_name='Categoría del producto')),
            ],
        ),
    ]
