# Generated by Django 5.2.7 on 2025-11-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
    ]
