# Generated by Django 5.2.7 on 2025-10-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asistente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consulta', models.TextField(verbose_name='descripcion de la consulta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
    ]
