# Generated by Django 5.2.7 on 2025-10-10 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='envio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección de envío')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de envio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_compras.compra', verbose_name='Compra asociada')),
            ],
        ),
    ]
