# Generated by Django 5.2.7 on 2025-11-09 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_compras', '0003_articulo_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='documento_facturacion',
            field=models.CharField(default=datetime.datetime(2025, 11, 9, 16, 40, 55, 34411, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='Número de documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='email_facturacion',
            field=models.EmailField(default=datetime.datetime(2025, 11, 9, 16, 41, 1, 618094, tzinfo=datetime.timezone.utc), max_length=254, verbose_name='Email de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_facturacion',
            field=models.CharField(default=datetime.datetime(2025, 11, 9, 16, 41, 8, 864161, tzinfo=datetime.timezone.utc), max_length=200, verbose_name='Nombre completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='requiere_envio',
            field=models.BooleanField(default=True, verbose_name='Requiere envío a domicilio'),
        ),
        migrations.AddField(
            model_name='compra',
            name='telefono_facturacion',
            field=models.CharField(default=datetime.datetime(2025, 11, 9, 16, 41, 18, 7341, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Teléfono de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='envio',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='envio',
            name='notas_adicionales',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
    ]
